# Copied from https://www.sphinx-doc.org/en/master/tutorial/deploying.html#id6

stages:
  - deploy

pages:
  stage: deploy
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx furo rst2pdf
  script:
    - cd docs && make html && make latexpdf
  after_script:
    - mv docs/build/html/ ./public/
    - mv docs/build/latex/zenofreffing.pdf ./public/zen-roller-derby.pdf
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH